Complete the following box to setup your configuration

In [1]:
from docplex.cp.model import *
context.solver.agent = 'local'
#context.solver.local.execfile = 'Path to the binary cpoptimizer' --> At INSA we use the following: 
context.solver.local.execfile = '/usr/local/insa/ibm_cplex_studio_2211/cpoptimizer/bin/x86-64_linux/cpoptimizer'
context.verbose = 0



#The solver's documentation is here 
#https://ibmdecisionoptimization.github.io/docplex-doc/cp/index.html

Please use the following parameters each time you call the solver 

In [2]:
myparams = CpoParameters(TimeLimit= 20,
                            LogVerbosity="Quiet" ,
                             SearchType = 'DepthFirst',
                             Presolve = 'Off',
                             Workers=  1,
                             RandomSeed = 2)

You can add as many cells as you want. Make sure to choose "Markdown" instead of "code" if you want to write in a natural language. 

When submitting your work, please re-execute the notebook from the start and do not remove the output. 

We want to set up a speed interview event between $n$ students and $n$ companies. Each student has a unique list that reflects his preferences towards companies. The first element is the most prefered company, the second one is the second most prefered, etc. For instance, if Alice's list of preferences is [4,1,3,2]. Then she prefers to be assigned to  company 4, then 1, then 3, then 2. Similarly, each company has a list of preferences towards students. The preferences represent a strict order (i.e., no ties). 

A matching $M$ is a one-to-one mapping from students to companies. Let $s$ be a student and $c$ be a company. The pair $(s,c)$ is unhappy in $M$ if they prefer to be together compared to their situation in $M$. That is, if $M[s] =c' $ and $ s' = M^{-1}[c]$ then $s$ prefers c than $c'$, and $c$ prefers $s$ than $s'$. 


The stable interview problem is the problem of finding a matching that has no unhappy pair. 

# Example 

The following code generates a random list of preferences

In [3]:
import numpy as np
import random

#Run The model 
# Example data
def generate_random_list(n) : 
    my_list = [i for i in range (n)]
    return random.sample(my_list, len(my_list))

To generate a random instance of the speed interview problem, we use the following function 

In [4]:
#Gererate an instance of size $6$
def generate_random_instance(n) : 

    s = [generate_random_list(n) for i in range(n)]
    c = [generate_random_list(n) for i in range(n)]
    return s, c


Generate a random instance of size 4

In [5]:
#Example with n= 6
n=4 
students_preferences, companies_preferences = generate_random_instance(n)

print("\nstudents_preferences:")
print(np.matrix(students_preferences))

print("\ncompanies_preferences Preferences:")
print(np.matrix(companies_preferences))



students_preferences:
[[1 3 2 0]
 [0 3 2 1]
 [0 1 2 3]
 [3 2 1 0]]

companies_preferences Preferences:
[[2 3 0 1]
 [3 2 0 1]
 [3 1 0 2]
 [0 2 1 3]]




Complete the following function to model the stable interview problem. Do not call the solver to search for solutions in this function. We will do it saperately later. 


You can use the element expression if you want (but it is not mandatory) :  https://ibmdecisionoptimization.github.io/docplex-doc/cp/docplex.cp.modeler.py.html?highlight=element#docplex.cp.modeler.element

In [6]:
def stable_interview (n, students_preferences, companies_preferences):
        
    return ... 

Test your function on an instance of size n= 10. Ask the solver to generate only one solution

How many decisions are made ? 

How many failures are made ? 

What is the runtime ? 

Without changing your model, did you use an implied constraint? if yes, which one ? If no, can you find one (again without modifying the model) ? 

We want to setup a user-friendly solution printer. Let $CompanyOf[s]$ be the company to which student $s$ is matched. Similarly, we denote by $StudentOf[c]$ the student assigned to company $c$. 


Solve again the problem for n= 10, construct the lists $CompanyOf$ and  $StudentOf$, then print them. 

We want to automate the experiments. Complete the following function that takes as input n, generates a new random instance, solve it, then returns the search status, the number of decisions, the number of failures, and the runtime

In [7]:
def run_decision_version(n) : 
    
    ...
    return status, nb_decisions, nb_failures, runtime

Test your function with a random instance. Print the status, the number of decisions, the number of failures, and the runtime

Test the run function with four different sizes


Find 10 different numbers $n_1 > n_2, \ldots > n_{10}$ such that the solver needs between $10$s to $20$s to find a solution for each size

Choose two completely different search strategies, then run them on a random instance

Run an experimental study to campare the two search strategies in terms of the number of decisions and runtime on 20 instances of different sizes of your choice. We expect to have a visual comparision in the form of plots

We want to give more previlage to students. Let $M$ be a solution and let $Index[s]$ be the index of $M[s]$ in the preference list of $s$. We want to minimize the maximum value of $\{Index[1], \ldots Index[N] \}$. Complete the following function to model for this optimisation problem. 

In [8]:
def optimal_stable_interview (n, students_preferences, companies_preferences):
        
    return 

Test your model